zshrc: add keychain autoexec.

diff --git a/files/zshrc b/files/zshrc
--- a/files/zshrc
+++ b/files/zshrc
@@ -100,6 +100,15 @@ if [[ $#h -gt 0 ]]; then
   zstyle ':completion:*:slogin:*' hosts $h
 fi
 
+# If keychain is installed, start it silently
+type "keychain" > /dev/null
+if [[ ( !$? ) && ( -f ~/.ssh/id_rsa ) ]]; then
+	keychain ~/.ssh/id_rsa
+	HOSTNAME=`uname -n`
+	. ~/.keychain/$HOSTNAME-sh
+	. ~/.keychain/$HOSTNAME-sh-gpg
+fi
+
 if [ -f ~/.zshrc.more ]; then
 	source ~/.zshrc.more
 fi
